In [2]:
import pandas as pd
from pandas import DataFrame
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data2.xlsx')

In [3]:
name='삼덕동'
df = DataFrame(columns=("나이",name))
df2=[]
for i in range(0,21):
    k=6*i
  # print("i 값은",k)
    df.loc[i]=xlsx['Unnamed: 0'][2+k],xlsx[name][2+k]

for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
134
212
233
262
545
963
612
568
504
647
650
701
714
547
523
438
278
143
57
11
13


hi
240
263
178
202
705
1140
667
576
464
420
382
329
331
243
195
179
114
68
25
5
7


hi
72
97
96
144
590
810
467
302
259
306
307
328
349
222
225
216
126
67
37
6
7


hi
67
67
80
117
346
492
306
229
220
278
347
411
417
379
317
249
149
77
31
10
15


hi
310
260
89
146
312
342
456
602
357
340
340
396
371
288
223
186
123
44
20
8
5


hi
513
401
256
308
410
419
598
852
561
615
648
598
617
443
351
303
189
84
25
10
11


hi
120
159
122
191
373
487
324
356
317
340
414
412
407
294
266
275
176
71
11
7
2


hi
105
105
103
162
291
323
272
282
229
324
331
309
272
249
245
188
128
76
22
9
14


hi
283
330
273
258
367
354
421
572
568
568
546
539
525
423
369
328
211
96
30
5
4


hi
403
567
515
575
697
647
605
817
910
1031
938
885
907
778
641
503
393
164
48
16
9


hi
271
285
266
357
495
501
445
496
525
650
618
588
541
404
373
370
269
126
43
12
8


hi
35
43
60
104
117
140
106
110
143
237
209
206
209
196
224
186
101
51
18
3
6


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동', '남산4동', '대봉1동', '대봉2동'],
      dtype='object')

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,남산4동,대봉1동,대봉2동
0,0∼4세,240,134,72,67,310,513,120,105,283,403,271,35
1,5∼9세,263,212,97,67,260,401,159,105,330,567,285,43
2,10∼14세,178,233,96,80,89,256,122,103,273,515,266,60
3,15∼19세,202,262,144,117,146,308,191,162,258,575,357,104
4,20∼24세,705,545,590,346,312,410,373,291,367,697,495,117
5,25∼29세,1140,963,810,492,342,419,487,323,354,647,501,140
6,30∼34세,667,612,467,306,456,598,324,272,421,605,445,106
7,35∼39세,576,568,302,229,602,852,356,282,572,817,496,110
8,40∼44세,464,504,259,220,357,561,317,229,568,910,525,143
9,45∼49세,420,647,306,278,340,615,340,324,568,1031,650,237
10,50∼54세,382,650,307,347,340,648,414,331,546,938,618,209
11,55∼59세,329,701,328,411,396,598,412,309,539,885,588,206
12,60∼64세,331,714,349,417,371,617,407,272,525,907,541,209
13,65∼69세,243,547,222,379,288,443,294,249,423,778,404,196
14,70∼74세,195,523,225,317,223,351,266,245,369,641,373,224
15,75∼79세,179,438,216,249,186,303,275,188,328,503,370,186
16,80∼84세,114,278,126,149,123,189,176,128,211,393,269,101
17,85∼89세,68,143,67,77,44,84,71,76,96,164,126,51
18,90∼94세,25,57,37,31,20,25,11,22,30,48,43,18
19,95∼99세,5,11,6,10,8,10,7,9,5,16,12,3
20,100세이상,7,13,7,15,5,11,2,14,4,9,8,6

In [4]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data3.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]
for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
125
165
198
284
428
457
350
379
438
567
646
764
768
667
548
549
355
158
46
12
5


hi
487
609
493
363
502
524
647
884
1009
892
786
766
784
635
536
478
284
152
39
12
10


hi
327
400
268
325
467
519
570
732
587
637
686
736
785
601
473
375
272
98
38
12
3


hi
201
275
304
422
833
1066
769
770
748
1056
1258
1395
1304
1006
771
588
350
140
50
10
10


hi
90
149
167
248
411
394
282
306
349
522
577
683
703
550
442
363
265
97
26
4
4


hi
382
498
416
538
732
802
748
861
927
1043
1114
1133
1141
942
758
723
442
227
49
17
7


hi
413
549
512
537
897
778
701
937
926
1035
1138
1083
942
677
540
429
309
156
42
11
8


hi
58
109
150
219
471
843
589
472
471
551
638
693
671
584
400
339
221
101
30
5
4


hi
242
321
334
564
875
963
713
760
780
1008
1221
1437
1427
1194
947
780
525
183
61
11
10


hi
358
441
475
590
880
1056
808
908
995
1162
1201
1358
1431
1134
883
646
444
212
69
11
10


hi
102
100
123
150
270
348
242
216
208
306
357
396
388
306
249
219
144
74
16
3
0


hi
1127
1581
1402
1330
1458
1496
1380
2164
2334
2294
2146
2104
1963
1448
989
729
470
207
74
13
4


hi
201
208
216
385
631
713
541
491
530
725
961
1130
1169
762
622
498
293
131
34
8
5


hi
447
461
381
579
1004
1200
954
1019
955
1134
1447
1635
1521
1191
823
745
455
179
59
15
2


hi
379
555
574
808
1195
1229
877
959
1047
1334
1694
1939
1813
1368
997
848
545
282
73
16
6


hi
364
447
409
540
869
1045
832
868
892
1090
1368
1510
1483
1251
940
755
488
194
65
19
2


hi
1673
2341
1914
1868
2614
2765
2558
3438
3446
3489
3471
3666
3506
2547
1767
1428
929
452
152
26
7


hi
318
310
250
394
640
738
597
696
610
773
1002
1123
1029
781
612
483
270
126
44
6
6


hi
3964
4444
3738
3435
3765
4269
5445
6865
6386
6153
4876
4284
3957
2921
2132
1598
964
443
127
39
13


hi
281
421
487
656
822
768
593
755
880
1287
1382
1558
1494
1338
1069
905
627
314
86
18
7


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동', '남산4동', '대봉1동', '대봉2동', '신암 1동', '신암 2동', '신암 3동', '신암 4동',
       '신암 5동', '신천 1.2동', '신천 3동', '신천 4동', '효목 1동', '효목 2동', '도평동', '불로봉무동',
       '지저동', '동촌동', '방촌동', '해안동', '안심1동', '안심2동', '안심3.4동', '공산동'],
      dtype='object')

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,도평동,불로봉무동,지저동,동촌동,방촌동,해안동,안심1동,안심2동,안심3.4동,공산동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,102,1127,201,447,379,364,1673,318,3964,281
1,5∼9세,263,212,97,67,260,401,159,105,330,...,100,1581,208,461,555,447,2341,310,4444,421
2,10∼14세,178,233,96,80,89,256,122,103,273,...,123,1402,216,381,574,409,1914,250,3738,487
3,15∼19세,202,262,144,117,146,308,191,162,258,...,150,1330,385,579,808,540,1868,394,3435,656
4,20∼24세,705,545,590,346,312,410,373,291,367,...,270,1458,631,1004,1195,869,2614,640,3765,822
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,348,1496,713,1200,1229,1045,2765,738,4269,768
6,30∼34세,667,612,467,306,456,598,324,272,421,...,242,1380,541,954,877,832,2558,597,5445,593
7,35∼39세,576,568,302,229,602,852,356,282,572,...,216,2164,491,1019,959,868,3438,696,6865,755
8,40∼44세,464,504,259,220,357,561,317,229,568,...,208,2334,530,955,1047,892,3446,610,6386,880
9,45∼49세,420,647,306,278,340,615,340,324,568,...,306,2294,725,1134,1334,1090,3489,773,6153,1287
10,50∼54세,382,650,307,347,340,648,414,331,546,...,357,2146,961,1447,1694,1368,3471,1002,4876,1382
11,55∼59세,329,701,328,411,396,598,412,309,539,...,396,2104,1130,1635,1939,1510,3666,1123,4284,1558
12,60∼64세,331,714,349,417,371,617,407,272,525,...,388,1963,1169,1521,1813,1483,3506,1029,3957,1494
13,65∼69세,243,547,222,379,288,443,294,249,423,...,306,1448,762,1191,1368,1251,2547,781,2921,1338
14,70∼74세,195,523,225,317,223,351,266,245,369,...,249,989,622,823,997,940,1767,612,2132,1069
15,75∼79세,179,438,216,249,186,303,275,188,328,...,219,729,498,745,848,755,1428,483,1598,905
16,80∼84세,114,278,126,149,123,189,176,128,211,...,144,470,293,455,545,488,929,270,964,627
17,85∼89세,68,143,67,77,44,84,71,76,96,...,74,207,131,179,282,194,452,126,443,314
18,90∼94세,25,57,37,31,20,25,11,22,30,...,16,74,34,59,73,65,152,44,127,86
19,95∼99세,5,11,6,10,8,10,7,9,5,...,3,13,8,15,16,19,26,6,39,18
20,100세이상,7,13,7,15,5,11,2,14,4,...,0,4,5,2,6,2,7,6,13,7

In [5]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data4.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]
for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
160
197
212
334
622
731
493
496
487
610
801
929
899
637
472
356
226
109
23
3
10


hi
162
188
216
347
614
695
472
520
573
784
957
1091
1054
887
673
576
365
131
42
6
7


hi
333
455
544
763
1152
1327
1022
986
989
1318
1533
1697
1637
1199
927
615
401
207
61
12
2


hi
124
200
266
382
556
620
417
486
557
815
1035
1114
972
796
610
506
302
117
39
12
8


hi
123
192
215
302
467
602
395
435
474
722
908
1060
1038
832
694
689
411
153
50
14
18


hi
167
227
241
399
671
656
495
506
595
752
968
1089
1046
818
566
474
309
123
28
13
11


hi
93
119
146
227
318
372
333
299
350
474
603
718
691
591
429
393
246
101
26
1
1


hi
95
125
178
331
484
551
349
362
384
667
779
917
855
598
424
394
235
107
25
5
7


hi
182
207
229
379
592
765
517
526
596
895
1186
1299
1113
929
671
536
322
99
33
3
4


hi
108
192
201
310
505
532
363
386
436
634
825
859
832
625
429
430
239
105
27
10
6


hi
287
369
288
310
429
507
444
554
589
663
712
807
776
529
412
300
180
71
24
6
1


hi
149
207
232
416
629
686
527
500
570
819
1044
1225
1083
791
578
416
276
95
39
9
3


hi
622
765
593
663
1066
1278
1048
1354
1254
1368
1634
1892
1623
1236
820
572
354
174
70
15
4


hi
34
59
42
80
109
132
85
113
120
148
187
224
213
164
112
86
46
13
5
1
6


hi
61
107
138
208
317
333
228
278
268
436
561
633
613
466
284
234
151
76
18
3
0


hi
518
833
796
939
1357
1360
1031
1248
1421
1639
1897
2133
1976
1403
914
605
376
171
68
24
12


hi
118
163
170
265
446
542
348
383
479
626
802
836
779
670
483
428
266
124
32
3
0


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동', '남산4동', '대봉1동', '대봉2동', '신암 1동', '신암 2동', '신암 3동', '신암 4동',
       '신암 5동', '신천 1.2동', '신천 3동', '신천 4동', '효목 1동', '효목 2동', '도평동', '불로봉무동',
       '지저동', '동촌동', '방촌동', '해안동', '안심1동', '안심2동', '안심3.4동', '공산동', '내당1동',
       '내당2.3동', '내당4동', '비산1동', '비산2.3동', '비산4동', '비산5동', '비산6동', '비산7동',
       '평리1동', '평리2동', '평리3동', '평리4동', '평리5동', '평리6동', '상중이동', '원대동'],
      dtype='object')

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,비산6동,비산7동,평리1동,평리2동,평리3동,평리4동,평리5동,평리6동,상중이동,원대동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,95,182,108,287,149,622,34,61,518,118
1,5∼9세,263,212,97,67,260,401,159,105,330,...,125,207,192,369,207,765,59,107,833,163
2,10∼14세,178,233,96,80,89,256,122,103,273,...,178,229,201,288,232,593,42,138,796,170
3,15∼19세,202,262,144,117,146,308,191,162,258,...,331,379,310,310,416,663,80,208,939,265
4,20∼24세,705,545,590,346,312,410,373,291,367,...,484,592,505,429,629,1066,109,317,1357,446
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,551,765,532,507,686,1278,132,333,1360,542
6,30∼34세,667,612,467,306,456,598,324,272,421,...,349,517,363,444,527,1048,85,228,1031,348
7,35∼39세,576,568,302,229,602,852,356,282,572,...,362,526,386,554,500,1354,113,278,1248,383
8,40∼44세,464,504,259,220,357,561,317,229,568,...,384,596,436,589,570,1254,120,268,1421,479
9,45∼49세,420,647,306,278,340,615,340,324,568,...,667,895,634,663,819,1368,148,436,1639,626
10,50∼54세,382,650,307,347,340,648,414,331,546,...,779,1186,825,712,1044,1634,187,561,1897,802
11,55∼59세,329,701,328,411,396,598,412,309,539,...,917,1299,859,807,1225,1892,224,633,2133,836
12,60∼64세,331,714,349,417,371,617,407,272,525,...,855,1113,832,776,1083,1623,213,613,1976,779
13,65∼69세,243,547,222,379,288,443,294,249,423,...,598,929,625,529,791,1236,164,466,1403,670
14,70∼74세,195,523,225,317,223,351,266,245,369,...,424,671,429,412,578,820,112,284,914,483
15,75∼79세,179,438,216,249,186,303,275,188,328,...,394,536,430,300,416,572,86,234,605,428
16,80∼84세,114,278,126,149,123,189,176,128,211,...,235,322,239,180,276,354,46,151,376,266
17,85∼89세,68,143,67,77,44,84,71,76,96,...,107,99,105,71,95,174,13,76,171,124
18,90∼94세,25,57,37,31,20,25,11,22,30,...,25,33,27,24,39,70,5,18,68,32
19,95∼99세,5,11,6,10,8,10,7,9,5,...,5,3,10,6,9,15,1,3,24,3
20,100세이상,7,13,7,15,5,11,2,14,4,...,7,4,6,1,3,4,6,0,12,0

In [6]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data5.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]
for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
350
496
499
561
629
631
584
766
905
1147
998
973
921
834
709
681
482
253
96
24
8


hi
202
201
236
297
490
635
569
590
641
728
815
849
803
669
500
425
353
195
43
10
7


hi
309
383
418
479
551
569
514
627
698
814
896
934
1023
830
642
509
388
233
82
16
6


hi
379
507
609
801
1019
1049
860
1083
1149
1466
1457
1507
1578
1180
873
798
582
299
83
14
11


hi
234
325
352
438
802
948
708
738
716
897
1025
1028
1031
777
634
466
303
131
59
14
3


hi
194
223
271
428
1019
1067
728
687
638
858
879
995
948
770
665
549
363
190
52
11
6


hi
183
205
255
401
717
794
573
599
649
889
921
1132
1070
885
702
575
374
166
56
11
10


hi
227
260
252
393
791
878
612
608
600
817
987
1091
1134
881
656
555
351
139
38
8
8


hi
132
167
166
302
727
852
495
478
411
617
651
685
679
552
447
406
268
135
35
8
5


hi
239
334
307
334
623
779
646
726
679
746
753
821
795
621
469
382
264
139
41
10
4


hi
364
460
386
555
1073
1335
1025
1151
1101
1230
1421
1309
1341
1017
821
671
422
212
71
14
11


hi
160
193
216
302
608
786
585
574
552
653
813
826
889
734
524
467
316
157
40
13
2


hi
137
188
173
274
433
565
434
502
445
626
696
866
883
804
529
457
306
130
39
9
3


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동', '남산4동', '대봉1동', '대봉2동', '신암 1동', '신암 2동', '신암 3동', '신암 4동',
       '신암 5동', '신천 1.2동', '신천 3동', '신천 4동', '효목 1동', '효목 2동', '도평동', '불로봉무동',
       '지저동', '동촌동', '방촌동', '해안동', '안심1동', '안심2동', '안심3.4동', '공산동', '내당1동',
       '내당2.3동', '내당4동', '비산1동', '비산2.3동', '비산4동', '비산5동', '비산6동', '비산7동',
       '평리1동', '평리2동', '평리3동', '평리4동', '평리5동', '평리6동', '상중이동', '원대동', '이천동',
       '봉덕1동', '봉덕2동', '봉덕3동', '대명1동', '대명2동', '대명3동', '대명4동', '대명5동', '대명6동',
       '대명9동', '대명10동', '대명11동'],
      dtype='object')

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,봉덕3동,대명1동,대명2동,대명3동,대명4동,대명5동,대명6동,대명9동,대명10동,대명11동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,379,234,194,183,227,132,239,364,160,137
1,5∼9세,263,212,97,67,260,401,159,105,330,...,507,325,223,205,260,167,334,460,193,188
2,10∼14세,178,233,96,80,89,256,122,103,273,...,609,352,271,255,252,166,307,386,216,173
3,15∼19세,202,262,144,117,146,308,191,162,258,...,801,438,428,401,393,302,334,555,302,274
4,20∼24세,705,545,590,346,312,410,373,291,367,...,1019,802,1019,717,791,727,623,1073,608,433
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,1049,948,1067,794,878,852,779,1335,786,565
6,30∼34세,667,612,467,306,456,598,324,272,421,...,860,708,728,573,612,495,646,1025,585,434
7,35∼39세,576,568,302,229,602,852,356,282,572,...,1083,738,687,599,608,478,726,1151,574,502
8,40∼44세,464,504,259,220,357,561,317,229,568,...,1149,716,638,649,600,411,679,1101,552,445
9,45∼49세,420,647,306,278,340,615,340,324,568,...,1466,897,858,889,817,617,746,1230,653,626
10,50∼54세,382,650,307,347,340,648,414,331,546,...,1457,1025,879,921,987,651,753,1421,813,696
11,55∼59세,329,701,328,411,396,598,412,309,539,...,1507,1028,995,1132,1091,685,821,1309,826,866
12,60∼64세,331,714,349,417,371,617,407,272,525,...,1578,1031,948,1070,1134,679,795,1341,889,883
13,65∼69세,243,547,222,379,288,443,294,249,423,...,1180,777,770,885,881,552,621,1017,734,804
14,70∼74세,195,523,225,317,223,351,266,245,369,...,873,634,665,702,656,447,469,821,524,529
15,75∼79세,179,438,216,249,186,303,275,188,328,...,798,466,549,575,555,406,382,671,467,457
16,80∼84세,114,278,126,149,123,189,176,128,211,...,582,303,363,374,351,268,264,422,316,306
17,85∼89세,68,143,67,77,44,84,71,76,96,...,299,131,190,166,139,135,139,212,157,130
18,90∼94세,25,57,37,31,20,25,11,22,30,...,83,59,52,56,38,35,41,71,40,39
19,95∼99세,5,11,6,10,8,10,7,9,5,...,14,14,11,11,8,8,10,14,13,9
20,100세이상,7,13,7,15,5,11,2,14,4,...,11,3,6,10,8,5,4,11,2,3

In [7]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data6.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]
for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
159
147
152
207
276
326
291
338
320
389
424
445
452
381
282
260
142
81
24
6
5


hi
1113
1351
1019
1041
1225
1489
1611
2087
2115
1916
1683
1649
1481
1127
871
731
523
260
79
26
10


hi
84
99
84
152
228
264
232
218
209
282
409
549
489
375
254
184
100
51
22
5
2


hi
954
1387
1202
1072
1171
1005
1193
1772
1834
1871
1536
1249
1060
798
545
479
309
115
36
16
3


hi
778
1045
1102
1247
1389
1065
1065
1416
1638
1921
1856
1622
1351
1000
795
646
421
209
46
8
5


hi
376
318
269
385
634
788
836
789
777
915
1056
1399
1216
970
717
513
236
112
35
5
7


hi
113
161
206
306
492
573
362
401
511
669
890
1071
1060
929
683
610
421
164
35
7
5


hi
247
383
400
560
898
830
573
635
605
947
1100
1227
995
692
468
412
250
109
39
6
1


hi
132
173
194
321
1120
1247
650
471
504
608
637
668
660
535
421
327
233
96
25
7
3


hi
122
202
203
302
557
720
524
502
478
603
787
834
876
673
517
396
259
108
37
2
0


hi
96
102
119
276
1030
1156
561
446
368
472
605
612
596
393
284
215
141
60
15
1
1


hi
921
1198
1276
1724
2166
1832
1546
1833
2060
2462
2597
2423
2103
1291
867
635
432
242
79
15
7


hi
601
724
534
659
1430
1389
1027
1277
1296
1422
1486
1520
1452
1247
916
869
531
242
86
17
16


hi
169
189
206
255
370
413
429
445
431
500
563
718
708
547
379
304
196
99
24
4
1


hi
1420
1771
1750
2074
1962
1652
1768
2552
2886
3708
3073
2335
2073
1573
1069
779
433
186
57
9
1


hi
2258
2411
1638
1528
1991
2068
2795
3911
3253
3161
3008
2954
2476
1586
1084
770
430
225
59
11
4


hi
684
755
764
1092
1965
1755
1415
1316
1431
1840
2099
2172
1786
1154
793
659
455
234
69
13
2


hi
744
967
1113
1481
2016
1723
1311
1532
1735
2318
2411
2343
1884
1257
920
700
409
171
54
16
1


hi
1120
1736
2286
2960
3127
2255
1602
2025
2846
4284
3995
3101
2026
1096
814
777
495
226
78
14
0


hi
388
634
704
981
1373
1143
826
858
1037
1606
1831
1759
1525
965
590
547
383
170
46
7
3


hi
790
1006
1107
1528
2269
2104
1542
1595
1617
2407
2751
2760
2132
1238
840
737
504
279
63
11
6


hi
933
1548
2068
2540
2577
1604
1327
1675
2523
3761
3155
2116
1204
664
577
563
401
161
32
5
1


hi
900
1396
1533
1747
1790
1591
1249
1698
2067
2724
2388
1744
1043
725
540
526
335
160
48
11
2


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동', '남산4동', '대봉1동', '대봉2동', '신암 1동', '신암 2동', '신암 3동', '신암 4동',
       '신암 5동', '신천 1.2동', '신천 3동', '신천 4동', '효목 1동', '효목 2동', '도평동', '불로봉무동',
       '지저동', '동촌동', '방촌동', '해안동', '안심1동', '안심2동', '안심3.4동', '공산동', '내당1동',
       '내당2.3동', '내당4동', '비산1동', '비산2.3동', '비산4동', '비산5동', '비산6동', '비산7동',
       '평리1동', '평리2동', '평리3동', '평리4동', '평리5동', '평리6동', '상중이동', '원대동', '이천동',
       '봉덕1동', '봉덕2동', '봉덕3동', '대명1동', '대명2동', '대명3동', '대명4동', '대명5동', '대명6동',
       '대명9동', '대명10동', '대명11동', '고성동', '칠성동', '침산1동', '침산2동', '침산3동', '노원동',
       '산격1동', '산격2동', '산격3동', '산격4동', '복현1동', '복현2동', '대현동', '검단동', '무태조야동',
       '관문동', '태전1동', '태전2동', '구암동', '관음동', '읍내동', '동천동', '국우동'],
      dtype='object')

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,검단동,무태조야동,관문동,태전1동,태전2동,구암동,관음동,읍내동,동천동,국우동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,169,1420,2258,684,744,1120,388,790,933,900
1,5∼9세,263,212,97,67,260,401,159,105,330,...,189,1771,2411,755,967,1736,634,1006,1548,1396
2,10∼14세,178,233,96,80,89,256,122,103,273,...,206,1750,1638,764,1113,2286,704,1107,2068,1533
3,15∼19세,202,262,144,117,146,308,191,162,258,...,255,2074,1528,1092,1481,2960,981,1528,2540,1747
4,20∼24세,705,545,590,346,312,410,373,291,367,...,370,1962,1991,1965,2016,3127,1373,2269,2577,1790
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,413,1652,2068,1755,1723,2255,1143,2104,1604,1591
6,30∼34세,667,612,467,306,456,598,324,272,421,...,429,1768,2795,1415,1311,1602,826,1542,1327,1249
7,35∼39세,576,568,302,229,602,852,356,282,572,...,445,2552,3911,1316,1532,2025,858,1595,1675,1698
8,40∼44세,464,504,259,220,357,561,317,229,568,...,431,2886,3253,1431,1735,2846,1037,1617,2523,2067
9,45∼49세,420,647,306,278,340,615,340,324,568,...,500,3708,3161,1840,2318,4284,1606,2407,3761,2724
10,50∼54세,382,650,307,347,340,648,414,331,546,...,563,3073,3008,2099,2411,3995,1831,2751,3155,2388
11,55∼59세,329,701,328,411,396,598,412,309,539,...,718,2335,2954,2172,2343,3101,1759,2760,2116,1744
12,60∼64세,331,714,349,417,371,617,407,272,525,...,708,2073,2476,1786,1884,2026,1525,2132,1204,1043
13,65∼69세,243,547,222,379,288,443,294,249,423,...,547,1573,1586,1154,1257,1096,965,1238,664,725
14,70∼74세,195,523,225,317,223,351,266,245,369,...,379,1069,1084,793,920,814,590,840,577,540
15,75∼79세,179,438,216,249,186,303,275,188,328,...,304,779,770,659,700,777,547,737,563,526
16,80∼84세,114,278,126,149,123,189,176,128,211,...,196,433,430,455,409,495,383,504,401,335
17,85∼89세,68,143,67,77,44,84,71,76,96,...,99,186,225,234,171,226,170,279,161,160
18,90∼94세,25,57,37,31,20,25,11,22,30,...,24,57,59,69,54,78,46,63,32,48
19,95∼99세,5,11,6,10,8,10,7,9,5,...,4,9,11,13,16,14,7,11,5,11
20,100세이상,7,13,7,15,5,11,2,14,4,...,1,1,4,2,1,0,3,6,1,2

In [8]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data7.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]

for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
418
981
1071
1113
1182
879
614
986
1339
1647
1606
1315
998
727
609
514
373
159
46
10
5


hi
366
632
833
932
1177
1181
952
1038
1115
1446
1445
1184
1020
716
506
455
257
141
37
9
2


hi
792
1188
942
1099
1143
956
803
1388
1548
1723
1483
1091
747
503
392
325
221
105
39
7
8


hi
319
1222
2337
1921
1232
642
419
896
2083
2606
1740
987
741
570
476
369
236
130
40
9
1


hi
729
1226
1246
1351
1690
1313
938
1539
1739
2081
2189
1937
1646
1290
942
768
551
272
76
18
2


hi
215
334
471
764
956
952
616
611
706
1065
1146
998
876
646
468
373
282
140
36
5
2


hi
398
1015
1960
2064
1645
856
511
990
1928
2664
2123
1248
931
718
535
475
295
146
38
10
2


hi
516
841
1016
1225
1285
984
703
999
1398
1871
1767
1441
1236
1058
891
772
550
305
74
29
5


hi
318
854
929
846
710
534
411
801
1206
1287
973
843
753
619
449
388
220
131
28
3
5


hi
348
571
600
888
1139
1006
698
857
940
1359
1537
1395
1205
890
656
569
399
215
68
15
7


hi
632
1475
2060
2257
1739
1004
742
1320
2115
2876
2439
1756
1443
915
702
474
359
196
81
11
6


hi
213
368
371
536
817
981
693
713
789
1013
1025
926
821
668
516
449
265
119
47
8
1


hi
366
404
399
419
670
828
726
863
913
1013
1037
1005
962
741
563
474
329
155
53
7
3


hi
424
647
647
699
1013
1107
938
1167
1126
1399
1414
1505
1453
1114
827
674
422
252
86
20
7


hi
486
581
487
512
615
656
716
918
978
995
986
1078
1188
941
742
577
371
179
61
17
8


hi
443
522
508
690
1058
1186
883
992
1104
1259
1467
1279
1091
682
468
343
219
118
34
12
4


hi
456
642
770
1241
1721
1603
1124
1219
1369
1949
2175
2128
1963
1444
1109
952
608
343
114
19
5


hi
433
712
851
1060
1385
1211
926
1109
1206
1739
1855
1816
1642
1240
779
642
482
301
86
13
2


hi
162
239
266
471
753
683
449
523
584
819
992
1260
1309
1041
782
671
479
259
85
14
4


hi
406
711
844
988
1102
852
689
873
1216
1413
1450
1443
1401
945
560
412
281
136
54
11
3


hi
739
1623
2209
2655
2597
1895
1256
1644
2398
3404
3145
2772
2029
1190
794
709
521
256
86
17
4


hi
810
1261
1519
1920
2140
1751
1338
1667
2012
2682
2748
2407
2017
1301
923
692
561
284
98
21
5


hi
1018
1634
1971
2418
2789
2176
1557
2024
2464
3399
3653
3113
2117
1339
896
868
672
341
94
16
7


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동',
       ...
       '상동', '파동', '두산동', '지산1동', '지산2동', '범물1동', '범물2동', '고산1동', '고산2동',
       '고산3동'],
      dtype='object', length=109)

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,상동,파동,두산동,지산1동,지산2동,범물1동,범물2동,고산1동,고산2동,고산3동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,424,486,443,456,433,162,406,739,810,1018
1,5∼9세,263,212,97,67,260,401,159,105,330,...,647,581,522,642,712,239,711,1623,1261,1634
2,10∼14세,178,233,96,80,89,256,122,103,273,...,647,487,508,770,851,266,844,2209,1519,1971
3,15∼19세,202,262,144,117,146,308,191,162,258,...,699,512,690,1241,1060,471,988,2655,1920,2418
4,20∼24세,705,545,590,346,312,410,373,291,367,...,1013,615,1058,1721,1385,753,1102,2597,2140,2789
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,1107,656,1186,1603,1211,683,852,1895,1751,2176
6,30∼34세,667,612,467,306,456,598,324,272,421,...,938,716,883,1124,926,449,689,1256,1338,1557
7,35∼39세,576,568,302,229,602,852,356,282,572,...,1167,918,992,1219,1109,523,873,1644,1667,2024
8,40∼44세,464,504,259,220,357,561,317,229,568,...,1126,978,1104,1369,1206,584,1216,2398,2012,2464
9,45∼49세,420,647,306,278,340,615,340,324,568,...,1399,995,1259,1949,1739,819,1413,3404,2682,3399
10,50∼54세,382,650,307,347,340,648,414,331,546,...,1414,986,1467,2175,1855,992,1450,3145,2748,3653
11,55∼59세,329,701,328,411,396,598,412,309,539,...,1505,1078,1279,2128,1816,1260,1443,2772,2407,3113
12,60∼64세,331,714,349,417,371,617,407,272,525,...,1453,1188,1091,1963,1642,1309,1401,2029,2017,2117
13,65∼69세,243,547,222,379,288,443,294,249,423,...,1114,941,682,1444,1240,1041,945,1190,1301,1339
14,70∼74세,195,523,225,317,223,351,266,245,369,...,827,742,468,1109,779,782,560,794,923,896
15,75∼79세,179,438,216,249,186,303,275,188,328,...,674,577,343,952,642,671,412,709,692,868
16,80∼84세,114,278,126,149,123,189,176,128,211,...,422,371,219,608,482,479,281,521,561,672
17,85∼89세,68,143,67,77,44,84,71,76,96,...,252,179,118,343,301,259,136,256,284,341
18,90∼94세,25,57,37,31,20,25,11,22,30,...,86,61,34,114,86,85,54,86,98,94
19,95∼99세,5,11,6,10,8,10,7,9,5,...,20,17,12,19,13,14,11,17,21,16
20,100세이상,7,13,7,15,5,11,2,14,4,...,7,8,4,5,2,4,3,4,5,7

In [9]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data8.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]

for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
715
1091
964
1106
1462
1559
1265
1691
1751
1952
2106
2171
2103
1691
1181
843
545
226
62
22
8


hi
278
364
325
447
1005
1435
982
973
842
1130
1358
1381
1451
1074
820
744
443
176
56
11
6


hi
176
239
275
339
621
709
501
497
534
650
759
812
761
642
492
408
286
120
38
7
5


hi
827
1292
1069
1060
1364
1351
1215
1796
1934
2003
1961
1969
1566
1058
630
405
250
125
35
13
3


hi
1004
1207
1042
1358
2069
2278
1890
2032
1939
2306
2684
2584
2171
1427
926
660
382
142
55
12
2


hi
311
411
423
632
1130
1298
956
862
911
1188
1474
1544
1345
863
545
417
247
132
32
2
2


hi
612
775
786
973
1289
1229
1035
1303
1317
1513
1780
1608
1242
890
563
411
230
114
32
7
3


hi
843
1304
1620
2117
2756
2375
1696
1782
2219
3200
3595
3096
2109
1201
839
644
425
168
46
8
2


hi
844
1100
1279
1791
2549
2260
1661
1748
1945
2843
3405
3131
2046
1155
743
614
410
161
52
10
2


hi
598
817
1037
1598
2169
2002
1259
1276
1594
2276
2845
2434
1496
903
592
444
327
160
39
7
0


hi
426
499
618
845
1254
1324
1136
1018
1015
1430
1688
1915
1570
872
496
372
222
112
33
8
0


hi
648
840
981
1607
3542
3084
1997
1674
1965
2803
3402
3098
2217
1348
1042
789
581
257
80
16
1


hi
1741
3602
4449
3904
2706
1510
1587
3224
5137
5660
3672
2150
1658
1179
758
525
350
199
59
11
8


hi
253
392
452
767
975
911
610
748
1030
1328
1507
1622
1628
1480
1153
912
629
275
81
12
6


hi
4007
5232
4307
4154
4768
4526
4888
6960
6916
6771
6209
5700
4595
3185
1998
1500
956
469
139
19
17


hi
1258
1858
2153
2822
3057
2436
1953
2331
2837
3757
3833
3610
2996
1905
1227
855
650
353
106
20
5


hi
579
634
621
944
1619
2010
1574
1355
1150
1545
1877
2077
1823
1188
742
542
358
177
53
13
4


hi
187
215
240
368
670
638
564
611
552
734
985
1347
1443
1106
704
584
381
219
68
12
0


hi
1014
1441
1571
2194
2761
2426
1858
2162
2259
3093
3681
3820
3338
1987
1222
929
700
324
89
26
0


hi
385
507
525
852
1402
1525
1179
1164
1189
1580
1901
1978
1818
1388
958
753
512
206
64
13
3


hi
323
470
551
762
1224
1348
977
1024
1113
1360
1675
1878
1929
1391
976
827
556
269
90
18
7


hi
281
406
419
568
870
869
722
843
897
1099
1301
1368
1230
925
584
458
315
167
61
8
0


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동',
       ...
       '월성1동', '월성2동', '진천동', '상인1동', '상인2동', '상인3동', '도원동', '송현1동', '송현2동',
       '본동'],
      dtype='object', length=131)

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,월성1동,월성2동,진천동,상인1동,상인2동,상인3동,도원동,송현1동,송현2동,본동
0,0∼4세,240,134,72,67,310,513,120,105,283,...,1741,253,4007,1258,579,187,1014,385,323,281
1,5∼9세,263,212,97,67,260,401,159,105,330,...,3602,392,5232,1858,634,215,1441,507,470,406
2,10∼14세,178,233,96,80,89,256,122,103,273,...,4449,452,4307,2153,621,240,1571,525,551,419
3,15∼19세,202,262,144,117,146,308,191,162,258,...,3904,767,4154,2822,944,368,2194,852,762,568
4,20∼24세,705,545,590,346,312,410,373,291,367,...,2706,975,4768,3057,1619,670,2761,1402,1224,870
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,1510,911,4526,2436,2010,638,2426,1525,1348,869
6,30∼34세,667,612,467,306,456,598,324,272,421,...,1587,610,4888,1953,1574,564,1858,1179,977,722
7,35∼39세,576,568,302,229,602,852,356,282,572,...,3224,748,6960,2331,1355,611,2162,1164,1024,843
8,40∼44세,464,504,259,220,357,561,317,229,568,...,5137,1030,6916,2837,1150,552,2259,1189,1113,897
9,45∼49세,420,647,306,278,340,615,340,324,568,...,5660,1328,6771,3757,1545,734,3093,1580,1360,1099
10,50∼54세,382,650,307,347,340,648,414,331,546,...,3672,1507,6209,3833,1877,985,3681,1901,1675,1301
11,55∼59세,329,701,328,411,396,598,412,309,539,...,2150,1622,5700,3610,2077,1347,3820,1978,1878,1368
12,60∼64세,331,714,349,417,371,617,407,272,525,...,1658,1628,4595,2996,1823,1443,3338,1818,1929,1230
13,65∼69세,243,547,222,379,288,443,294,249,423,...,1179,1480,3185,1905,1188,1106,1987,1388,1391,925
14,70∼74세,195,523,225,317,223,351,266,245,369,...,758,1153,1998,1227,742,704,1222,958,976,584
15,75∼79세,179,438,216,249,186,303,275,188,328,...,525,912,1500,855,542,584,929,753,827,458
16,80∼84세,114,278,126,149,123,189,176,128,211,...,350,629,956,650,358,381,700,512,556,315
17,85∼89세,68,143,67,77,44,84,71,76,96,...,199,275,469,353,177,219,324,206,269,167
18,90∼94세,25,57,37,31,20,25,11,22,30,...,59,81,139,106,53,68,89,64,90,61
19,95∼99세,5,11,6,10,8,10,7,9,5,...,11,12,19,20,13,12,26,13,18,8
20,100세이상,7,13,7,15,5,11,2,14,4,...,8,6,17,5,4,0,0,3,7,0

In [10]:
xlsx = pd.read_excel('C:\\Users\kimjino\Desktop\data9.xlsx')
#df = DataFrame(columns=("나이",name))
df2=[]

for z in xlsx.columns:
    #print (k)
    if 'U' in z or '합'in z:
        print(' ')
    else :
        print('hi')
        for i in range(0,21):
            k=6*i
          # print("i 값은",k)
            print(xlsx[z][2+k])
            df2.append(xlsx[z][2+k])
        
        df[z]=df2
        df2=[]

print(df.columns)
df

hi
1604
1885
2054
2667
3361
3084
2537
2881
3163
4206
4953
4913
4105
2657
1795
1421
845
426
131
28
10


hi
528
633
738
995
1263
1143
955
1060
1336
1911
2027
1910
1459
873
601
531
390
191
62
9
4


hi
5968
6705
4986
4229
4737
5098
6877
9646
8812
7512
6668
6199
4705
3067
1981
1332
778
389
122
25
2


hi
152
272
258
256
388
314
294
390
452
537
628
755
891
728
569
435
393
225
84
16
4


hi
22
39
34
27
56
57
53
59
55
68
157
200
200
147
120
150
146
94
20
6
1


hi
1461
1240
902
820
1262
1488
1783
2351
1792
1782
1992
2372
2110
1430
977
709
473
222
62
8
0


hi
1328
1251
897
809
1238
1960
2247
2393
2001
1641
1633
1603
1506
993
763
566
405
200
62
10
3


hi
2664
2844
1969
1341
1093
1420
2584
4021
3434
2370
1551
1352
1234
845
468
331
262
113
44
4
2


hi
648
574
314
224
296
617
898
1049
801
631
598
621
603
467
353
326
293
154
39
7
1


Index(['나이', '삼덕동', '동인동', '성내1동', '성내2동', '성내3동', '대신동', '남산1동', '남산2동',
       '남산3동',
       ...
       '본동', '화원읍', '논공읍', '다사읍', '가창면', '하빈면', '옥포면', '현풍면', '유가면', '구지면'],
      dtype='object', length=140)

,나이,삼덕동,동인동,성내1동,성내2동,성내3동,대신동,남산1동,남산2동,남산3동,...,본동,화원읍,논공읍,다사읍,가창면,하빈면,옥포면,현풍면,유가면,구지면
0,0∼4세,240,134,72,67,310,513,120,105,283,...,281,1604,528,5968,152,22,1461,1328,2664,648
1,5∼9세,263,212,97,67,260,401,159,105,330,...,406,1885,633,6705,272,39,1240,1251,2844,574
2,10∼14세,178,233,96,80,89,256,122,103,273,...,419,2054,738,4986,258,34,902,897,1969,314
3,15∼19세,202,262,144,117,146,308,191,162,258,...,568,2667,995,4229,256,27,820,809,1341,224
4,20∼24세,705,545,590,346,312,410,373,291,367,...,870,3361,1263,4737,388,56,1262,1238,1093,296
5,25∼29세,1140,963,810,492,342,419,487,323,354,...,869,3084,1143,5098,314,57,1488,1960,1420,617
6,30∼34세,667,612,467,306,456,598,324,272,421,...,722,2537,955,6877,294,53,1783,2247,2584,898
7,35∼39세,576,568,302,229,602,852,356,282,572,...,843,2881,1060,9646,390,59,2351,2393,4021,1049
8,40∼44세,464,504,259,220,357,561,317,229,568,...,897,3163,1336,8812,452,55,1792,2001,3434,801
9,45∼49세,420,647,306,278,340,615,340,324,568,...,1099,4206,1911,7512,537,68,1782,1641,2370,631
10,50∼54세,382,650,307,347,340,648,414,331,546,...,1301,4953,2027,6668,628,157,1992,1633,1551,598
11,55∼59세,329,701,328,411,396,598,412,309,539,...,1368,4913,1910,6199,755,200,2372,1603,1352,621
12,60∼64세,331,714,349,417,371,617,407,272,525,...,1230,4105,1459,4705,891,200,2110,1506,1234,603
13,65∼69세,243,547,222,379,288,443,294,249,423,...,925,2657,873,3067,728,147,1430,993,845,467
14,70∼74세,195,523,225,317,223,351,266,245,369,...,584,1795,601,1981,569,120,977,763,468,353
15,75∼79세,179,438,216,249,186,303,275,188,328,...,458,1421,531,1332,435,150,709,566,331,326
16,80∼84세,114,278,126,149,123,189,176,128,211,...,315,845,390,778,393,146,473,405,262,293
17,85∼89세,68,143,67,77,44,84,71,76,96,...,167,426,191,389,225,94,222,200,113,154
18,90∼94세,25,57,37,31,20,25,11,22,30,...,61,131,62,122,84,20,62,62,44,39
19,95∼99세,5,11,6,10,8,10,7,9,5,...,8,28,9,25,16,6,8,10,4,7
20,100세이상,7,13,7,15,5,11,2,14,4,...,0,10,4,2,4,1,0,3,2,1

In [19]:
df=df.T

In [ ]:
df.to_csv('data.csv',encoding='utf-8-sig')

In [20]:
df

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
나이,0∼4세,5∼9세,10∼14세,15∼19세,20∼24세,25∼29세,30∼34세,35∼39세,40∼44세,45∼49세,...,55∼59세,60∼64세,65∼69세,70∼74세,75∼79세,80∼84세,85∼89세,90∼94세,95∼99세,100세이상
삼덕동,240,263,178,202,705,1140,667,576,464,420,...,329,331,243,195,179,114,68,25,5,7
동인동,134,212,233,262,545,963,612,568,504,647,...,701,714,547,523,438,278,143,57,11,13
성내1동,72,97,96,144,590,810,467,302,259,306,...,328,349,222,225,216,126,67,37,6,7
성내2동,67,67,80,117,346,492,306,229,220,278,...,411,417,379,317,249,149,77,31,10,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
하빈면,22,39,34,27,56,57,53,59,55,68,...,200,200,147,120,150,146,94,20,6,1
옥포면,1461,1240,902,820,1262,1488,1783,2351,1792,1782,...,2372,2110,1430,977,709,473,222,62,8,0
현풍면,1328,1251,897,809,1238,1960,2247,2393,2001,1641,...,1603,1506,993,763,566,405,200,62,10,3
유가면,2664,2844,1969,1341,1093,1420,2584,4021,3434,2370,...,1352,1234,845,468,331,262,113,44,4,2
구지면,648,574,314,224,296,617,898,1049,801,631,...,621,603,467,353,326,293,154,39,7,1